config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :users
  resources :posts
  resources :rooms do
    resources :messages
  end
  get '',to:'users#feed'
  get 'main' ,to: 'users#main'
  post 'main', to: 'users#login'
  get 'register',to: 'users#new'
  get 'feed' ,to: 'users#feed'
  get '/post', to:'posts#create'
  #profile
  get '/profile/:nickname', to: 'users#profile', as: "profile_user"
  post '/profile/:nickname/follow', to: 'users#follow' ,as: "follow_user"
  post '/profile/:nickname/unfollow', to: 'users#unfollow' ,as: "unfollow_user"

  #Admin
  post '/users/:id/approve', to: 'users#approve',as: "approve_user"
  post '/users/:id/ban', to: 'users#ban',as: "ban_user"
  post '/users/:id/unban', to: 'users#unban',as: "unban_user"

  #Like
  post 'post/:post_id/like', to: 'posts#like', as: "like_post"
  post 'post/:post_id/unlike', to: 'posts#unlike',as: "unlike_post"
  post 'comment/:comment_id/like', to: 'comments#like', as: "like_comment"
  post 'comment/:comment_id/unlike', to: 'comments#unlike',as: "unlike_comment"

  #chat
  get '/chat', to: 'rooms#index'
  get '/chat/:id',to: 'chats#show'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  validates :msg ,presence: true, length: {maximum: 500}
  has_many :likes ,dependent: :destroy
  has_many :user_likes ,through: :likes, source: :user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  include MainConcern
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :is_logged_in, only: %i[index edit update destroy]
  before_action :is_admin, only: %i[index update destroy]
  before_action :is_ban, only: %i[new like unlike create]
  # GET /comments
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  def show
    if(@comment)
      redirect_to @comment.post
    end
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  def unlike
    Like.find_by(comment_id:params[:comment_id] ,user_id:session[:user_id]).destroy
    if(request.referrer)
      redirect_to request.referrer
    end
  end

  def like
    Like.create(comment_id:params[:comment_id] ,user_id:session[:user_id])
    if(request.referrer)
      redirect_to request.referrer
    end
  end

  # POST /comments
  def create
    @comment = Comment.new(msg:comment_params["msg"],user_id:session[:user_id],post_id:session[:post_id])

    if @comment.save
      redirect_to @comment.post, notice: 'Comment was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /comments/1
  def update
    if @comment.update(comment_params)
      redirect_to @comment, notice: 'Comment was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /comments/1
  def destroy
    @comment.destroy
    redirect_to comments_url, notice: 'Comment was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:msg, :post_id, :user_id)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.haml
= form_for @comment do |form|
  - if @comment.errors.any?
    #error_explanation
      %h2
        = pluralize(@comment.errors.count, "error")
        prohibited this comment from being saved:
      %ul
        - @comment.errors.each do |error|
          %li= error.full_message
  .field.mb-3
    = form.text_field :msg, { class: "form-control", placeholder: "Say something..."}
  .actions
    = form.button :Submit ,class:'btn btn-primary'

app/views/comments/edit.html.haml
%h1 Editing comment

= render 'form'

= link_to 'Show', @comment
\|
= link_to 'Back', comments_path

app/views/comments/index.html.haml
.container
  %h1 Listing comments
  
  %table#myTable.table-striped.display{:style => "width:100%"}
    %thead
      %tr
        %th Id
        %th Post title
        %th User Nickname
        %th Msg
        %th
        %th
  
    %tbody
      - @comments.each do |comment|
        %tr
          %td= comment.id
          %td= comment.post.title
          %td= comment.user.nickname
          %td= comment.msg          
          %td= link_to 'Show', comment.post
          %td= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' }
  
  .d-flex
    = button_to "Users", users_path , method: :get,class:"btn btn-secondary"
    = button_to "Posts", posts_path , method: :get,class:"btn btn-secondary ms-3 "

app/views/comments/new.html.haml
%h1 New comment

= render 'form'

= link_to 'Back', comments_path

app/views/comments/show.html.haml
%p#notice= notice

%p
  %b Msg:
  = @comment.msg
%p
  %b Post:
  = @comment.post
%p
  %b User:
  = @comment.user

= link_to 'Edit', edit_comment_path(@comment)
\|
= link_to 'Back', comments_path