config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :users
  resources :posts
  resources :rooms do
    resources :messages
  end
  get '',to:'users#feed'
  get 'main' ,to: 'users#main'
  post 'main', to: 'users#login'
  get 'register',to: 'users#new'
  get 'feed' ,to: 'users#feed'
  get '/post', to:'posts#create'
  #profile
  get '/profile/:nickname', to: 'users#profile', as: "profile_user"
  post '/profile/:nickname/follow', to: 'users#follow' ,as: "follow_user"
  post '/profile/:nickname/unfollow', to: 'users#unfollow' ,as: "unfollow_user"

  #Admin
  post '/users/:id/approve', to: 'users#approve',as: "approve_user"
  post '/users/:id/ban', to: 'users#ban',as: "ban_user"
  post '/users/:id/unban', to: 'users#unban',as: "unban_user"

  #Like
  post 'post/:post_id/like', to: 'posts#like', as: "like_post"
  post 'post/:post_id/unlike', to: 'posts#unlike',as: "unlike_post"
  post 'comment/:comment_id/like', to: 'comments#like', as: "like_comment"
  post 'comment/:comment_id/unlike', to: 'comments#unlike',as: "unlike_comment"

  #chat
  get '/chat', to: 'rooms#index'
  get '/chat/:id',to: 'chats#show'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
	self.per_page = 10
	validates :username,:nickname ,presence: true ,uniqueness: true
	validates :password ,presence: true 
	#length: { in:8..15}
	has_secure_password
	validates_confirmation_of :password, :message => "password confirmation should match password"
	has_many :posts ,dependent: :destroy
	has_many :likes ,dependent: :destroy
	has_many :comments ,dependent: :destroy

	has_many :follower_follows, foreign_key: :followee_id, class_name: "Follow" 
    has_many :followers, through: :follower_follows, source: :follower
    has_many :followee_follows, foreign_key: :follower_id, class_name: "Follow"
    has_many :followees, through: :followee_follows, source: :followee
   	
   	has_one_attached :avatar

  	scope :all_except, ->(user) { where.not(id: user) }
  	after_create_commit { broadcast_prepend_to "users" }
  	has_many :messages
   	
    def get_feed_post
	   posts = []
	   self.followees.each do |f|
	     f.posts.each do |p|
	       posts.push(p)
	     end
	   end
	   return posts.sort().reverse
   	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  require 'will_paginate/array'
  include MainConcern
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :is_logged_in, only: %i[ index]
  before_action :is_admin, only: %i[index ban approve unban destroy]
  before_action :is_ban ,only: %i[follow unfollow]

  def main
    session[:user_id] = nil
    session[:post_id] = nil
  end

  def login
    @username = params[:username]
    @pass = params[:password]
    @user = User.find_by(username:@username)
    respond_to do |format|
      unless(@user.present? && @user.authenticate(@pass))
        format.html { redirect_to main_path , alert: "Username/password not valid" }
      else
        if(@user.status == 0)
          format.html { redirect_to main_path , alert: "Please wait approval" }
        elsif(@user.status == -1)
          format.html { redirect_to main_path , alert: "This account was banned. Plase contact admin" }
        end
        session[:user_id] = @user.id
        format.html{ redirect_to feed_path, alert: "Login successfully"}
      end
    end
  end

  def feed
    session[:post_id] = nil
    @posts = Post.all.order("created_at DESC").paginate(page:params[:page],per_page: 5)
    if(session[:user_id])
      #Login
      @user = User.find(session[:user_id])
      @posts_follow = @user.get_feed_post.paginate(page:params[:page],per_page: 5)
      respond_to do |format|
        format.html
        format.js
      end  
    else
      respond_to do |format|
        format.html
        format.js
      end      
    end
  end

  def profile
    if(session[:user_id])
      @self_user = User.find(session[:user_id])
    end
    @user = User.find_by(nickname:params[:nickname])
    #not found user
    unless(@user.present?)
      redirect_to feed_path ,alert: "Could not find this user."
      return
    else
    #found user
      if(@user.status == 0)
        redirect_to request.referrer, alert: "This user was not approved yet." 
      elsif(@user.status == -1)
        redirect_to request.referrer , alert: "This account was banned. Plase contact admin"
      end
      @posts = @user.posts.order("created_at DESC").paginate(page:params[:page],per_page: 5)
    end
  end

  def follow
    profile_user = User.find_by(nickname:params[:nickname])
    Follow.create(follower_id:session[:user_id],followee_id:profile_user.id)
    if(request.referrer)
      redirect_to request.referrer ,notice: "You just follow " + profile_user.nickname
    end
  end

  def unfollow
    profile_user = User.find_by(nickname:params[:nickname])
    Follow.find_by(follower_id:session[:user_id],followee_id:profile_user.id).destroy
    if(request.referrer)
      redirect_to request.referrer  ,notice: "You just unfollow " + profile_user.nickname
    end
  end

  def index
    @users = User.all
  end

  def approve
    @user = User.find(params[:id].to_i)
    console(@user.nickname)
    @user.update_attribute(:status,1)
    redirect_to users_path, notice: 'User was successfully updated.'
  end

  def ban
    @user = User.find(params[:id].to_i)
    console(@user.nickname)
    @user.update_attribute(:status,-1)
    redirect_to users_path, notice: 'User was successfully updated.'
  end

  def unban
    @user = User.find(params[:id].to_i)
    console(@user.nickname)
    @user.update_attribute(:status,1)
    redirect_to users_path, notice: 'User was successfully updated.'
  end

  # GET /users/1
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    is_right_user(params[:id].to_i)
  end

  # POST /users
  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user, notice: 'User was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:username, :nickname, :password, :password_confirmation,:page,:avatar)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_feedNotLogin.html.haml
- flash.each do |type, msg|
  .alert.alert-info.alert-dismissible.fade.show{:style => "z-index:9999;"}
    = msg
    %button.btn-close{"aria-label" => "Close", "data-bs-dismiss" => "alert", :type => "button"}
= render '/nav'
-# Create by
.header.d-flex.flex-column.justify-content-center.border-bottom.border-2.mt-5
  .row
    .col-4.border-end.border-2
      %img.rounded-circle{:alt => "Creator Image", :src => image_path("myImage.jpg"), :height => "300vh"}
    .col-8
      .header-content
        %h1
          I'm Tiew, the creator of this web
        %p.ps-4.pt-4
          Welcome to Small, the web blog referencing from Medium
          %br
          %br
          You need to got approval before login.
        %p.pt-4
          Contact Me :
          %a.ms-2{:href => "mailto:tiewclub9@gmail.com"}
            %img.email{:alt => "Email Icon", :src =>"https://cdn-icons-png.flaticon.com/512/95/95645.png",:style => "width:42px;height:42px;"}

-# Feed Body
.container
  = render 'posts'

app/views/users/_form.html.haml
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |message|
          %li= message

  .field.mb-3
    = f.label :avatar ,{ class: "form-label"}
    = f.file_field :avatar, { class: "form-control"}
  .field.mb-3
    = f.label :username ,{ class: "form-label"}
    = f.text_field :username , { class: "form-control", placeholder: "Username (Used for log in)"}
  .field.mb-3
    = f.label :nickname ,{ class: "form-label"}
    = f.text_field :nickname , { class: "form-control", placeholder: "Nickname (Showed in system)"}
  .field.mb-3
    = f.label :password,{ class: "form-label"}
    = f.password_field :password , { class: "form-control", placeholder: "Password"}
  .field.mb-3
    = f.label :password_confirmation,{ class: "form-label"}
    = f.password_field :password_confirmation , { class: "form-control", placeholder: "Must be same above"} 
  .actions
    = f.submit 'Save' ,class:'btn btn-primary'

app/views/users/_posts.html.haml
#posts.mt-5
  - @posts.each do |post| 
    .card.mb-4{:style => "width:100%;"}
      .row.g-0
        .col-md-8
          .card-body
            %h1.display-5.card-title
              %a.card-link.card-link-feed{:href => "/posts/#{post.id}",:method =>"get"}
                = post.title.truncate_words(5)
            %p.blockquote.card-text
              = post.body.to_plain_text.truncate_words(50)
            %p.card-text
              %small.text-muted 
                = post.created_at.to_formatted_s(:short)
                by
                %a{:href => profile_user_path(post.user.nickname),:method =>"get"}
                  = post.user.nickname
                |
                = pluralize(post.views,"view")
                |
                = pluralize(post.likes.count,"like")
                |
                = pluralize(post.comments.count,"comment")
        .col-md-4
          - if post.banner.attached?
            = image_tag(post.banner,style:"width:100%;height:300px;overflow-y:hidden")
          - else
            %img{:alt => "default banner",:src =>image_path("default_banner.jpg"),:style =>"width:100%;height:300px;overflow-y:hidden"}
#infinite-scrolling.digg_pagination
  = will_paginate(@posts)

app/views/users/_posts2.html.haml
#posts.mt-4
  - @posts.each do |post| 
    .card.mb-4{:style => "width:100%;"}
      .row.g-0
        .col-md-8
          .card-body
            %h6.display-6.fs-3.card-title
              %a.card-link.card-link-feed{:href => "/posts/#{post.id}",:method =>"get"}
                = post.title.truncate_words(5)
            %p.blockquote.card-text
              = post.body.to_plain_text.truncate_words(20)
            %p.card-text{:style => "font-size: 20px;"}
              %small.text-muted 
                = post.created_at.to_formatted_s(:short)
                by
                %a{:href => profile_user_path(post.user.nickname),:method =>"get"}
                  = post.user.nickname
                |
                = pluralize(post.views,"view")
                |
                = pluralize(post.likes.count,"like")
                |
                = pluralize(post.comments.count,"comment")
        .col-md-4
          - if post.banner.attached?
            = image_tag(post.banner,style:"width:100%;height:300px;overflow-y:hidden")
          - else
            %img{:alt => "default banner",:src =>image_path("default_banner.jpg"),:style =>"width:100%;height:300px;overflow-y:hidden"}
#infinite-scrolling.digg_pagination
  = will_paginate(@posts)

app/views/users/_profileLogin.html.haml
- flash.each do |type, msg|
  .alert.alert-info.alert-dismissible.fade.show{:style => "z-index:9999;"}
    = msg
    %button.btn-close{"aria-label" => "Close", "data-bs-dismiss" => "alert", :type => "button"}

.row
  .col-3.position-fixed.border-end.border-2
    = render '/nav2'

  .col-7.offset-3.ps-5.pe-5
    .container
      %nav.mt-3
        #nav-tab.nav.nav-tabs{:role => "tablist"}
          %button#nav-home-tab.nav-link.active{"aria-controls" => "nav-home", "aria-selected" => "true", "data-bs-target" => "#nav-home", "data-bs-toggle" => "tab", :role => "tab", :type => "button",:style =>"font-size:20px"} Posts
      #nav-tabContent.tab-content
        #nav-home.tab-pane.fade.show.active{"aria-labelledby" => "nav-home-tab", :role => "tabpanel"}
          = render 'posts2' 

  .col-2.offset-10.position-fixed.border-start.border-2
    = render 'profilebar'

app/views/users/_profilebar.html.haml
.nav.flex-column.flex-nowrap.vh-100.overflow-auto.text-white.p-2
  .container-fluid.d-flex.flex-column.align-items-center
    %a.navbar-brand.ms-5{:href => "/profile/#{@user.nickname}"}
      - if @user.avatar.attached?
        = image_tag(@user.avatar,:class => "rounded-circle mb-4 mt-5",:style => "width:200px;height:200px; overflow-y:hidden")
      - else
        %img.rounded-circle.mb-4.mt-5{:alt => "default avatar",:src =>image_path("default_avatar.png"),:style => "width:200px;height:200px; overflow-y:hidden"}      
    .d-flex.flex-column.align-items-start
      %a.navbar-brand.mt-3{:href => "/profile/#{@user.nickname}"}
        .d-flex.align-items-center
          %img.me-3{:alt => "profile icon", :height => "35px", :src => image_path("profile_icon.png"), :width => "35px"}
          %h2.display-6
            =@user.nickname
      %ul.nav.navbar-nav
        %li.nav-item
          %p.navbar-text.fs-4{:style => "color: black"}
            = pluralize(@user.followers.count,"follower")
      -if(session[:user_id] == @user.id)
        .dropdown
          %button#dropdownMenuButton1.btn.btn-secondary.dropdown-toggle{"aria-expanded" => "false", "data-bs-toggle" => "dropdown", :type => "button"}
            Account Settings
          %ul.dropdown-menu{"aria-labelledby" => "dropdownMenuButton1"}
            %li
              %a.dropdown-item{:href => edit_user_path(@user)} Edit User
            %li
              %a.dropdown-item{:href => main_path} Logout
      -else
        - if @self_user.followees.include?(@user)
          = button_to "Unfollow", "/profile/#{@user.nickname}/unfollow" , method: "POST",class:"btn btn-secondary "
        - else
          = button_to "Follow", "/profile/#{@user.nickname}/follow" , method: "POST" ,class:"btn btn-primary"

app/views/users/_user.html.haml
.card.mb-3{:style => "width:100%;"}
  .row.g-0
    .card-body
      %h6.display-6.fs-3.card-title
        %a.card-link.card-link-feed{:href => "/chat/#{user.id}",:method =>"get"}
          = user.nickname 

app/views/users/edit.html.haml
.container
	%h1 Editing user
	
	= render 'form'
	
	= button_to "Back", request.referrer , method: :get ,class:"btn btn-light mt-2"

app/views/users/feed.html.haml
-if(session[:user_id])
  =render 'feedLogin'
-else
  =render 'feedNotLogin'

app/views/users/feed.js.erb
$('#my-posts').append('<%= j render @posts %>');
<% if @posts.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate @posts %>');
<% else %>
  $(window).off('scroll');
  $('.pagination').remove();
<% end %>

app/views/users/index.html.haml
.container
  %h1 Listing users
  
  %table#myTable.table-striped.display{:style => "width:100%"}
    %thead
      %tr
        %th Id
        %th Username
        %th Nickname
        %th Status
        %th
        %th
        %th
  
    %tbody
      - @users.each do |user|
        -if(!user.admin && user.status != 2)
          %tr
            %td= user.id
            %td= user.username
            %td= user.nickname
            %td= user.status
            %td= link_to 'Show', user
            -if(user.status == 0)
              %td= link_to 'Approve', approve_user_path(user), method: :post
            -elsif(user.status == 1)
              %td= link_to 'Ban', ban_user_path(user), method: :post,data: { confirm: 'Are you sure?' }
            -elsif(user.status == -1)
              %td= link_to 'UnBan', unban_user_path(user), method: :post,data: { confirm: 'Are you sure?'  }
            %td= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }
  
  .d-flex
    = button_to "Posts", posts_path , method: :get,class:"btn btn-secondary"
    = button_to "Comments", comments_path , method: :get,class:"btn btn-secondary ms-3 "

app/views/users/main.html.haml
- flash.each do |type, msg|
  .alert.alert-danger.alert-dismissible.fade.show{:style => "z-index:9999;"}
    = msg
    %button.btn-close{"aria-label" => "Close", "data-bs-dismiss" => "alert", :type => "button"}

.main
  .card
    .card-body
      = form_with do |form|
        .field.mb-3
          = form.label :username,"Username : ",{ class: "form-label display-6"}
          = form.text_field :username, { class: "form-control-lg w-75 m-4", placeholder: "Username"}
        .field.mb-3
          = form.label :password ,"Password : ",{ class: "form-label display-6"}
          = form.password_field :password ,{ class: "form-control-lg w-75 m-4", placeholder: "Password"}
        .row
          .col
            = button_to "Log in" , "/main" ,class:"btn btn-primary ms-3 main-btn"
          .col
            = button_to "Register" , "/register",class:"btn btn-secondary ms-3 main-btn",method: "get"

app/views/users/new.html.haml
- flash.each do |type, msg|
  .alert.alert-info.alert-dismissible.fade.show{:style => "z-index:9999;"}
    = msg
    %button.btn-close{"aria-label" => "Close", "data-bs-dismiss" => "alert", :type => "button"}
= render '/nav'
.container
  %br
  %br
  %br
  %h1 Register User

  = render 'form'
	
  = link_to 'Cancel', feed_path

app/views/users/profile.html.haml
-if(session[:user_id])
  =render 'profileLogin'
-else
  =render 'profileNotLogin'