config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :users
  resources :posts
  resources :rooms do
    resources :messages
  end
  get '',to:'users#feed'
  get 'main' ,to: 'users#main'
  post 'main', to: 'users#login'
  get 'register',to: 'users#new'
  get 'feed' ,to: 'users#feed'
  get '/post', to:'posts#create'
  #profile
  get '/profile/:nickname', to: 'users#profile', as: "profile_user"
  post '/profile/:nickname/follow', to: 'users#follow' ,as: "follow_user"
  post '/profile/:nickname/unfollow', to: 'users#unfollow' ,as: "unfollow_user"

  #Admin
  post '/users/:id/approve', to: 'users#approve',as: "approve_user"
  post '/users/:id/ban', to: 'users#ban',as: "ban_user"
  post '/users/:id/unban', to: 'users#unban',as: "unban_user"

  #Like
  post 'post/:post_id/like', to: 'posts#like', as: "like_post"
  post 'post/:post_id/unlike', to: 'posts#unlike',as: "unlike_post"
  post 'comment/:comment_id/like', to: 'comments#like', as: "like_comment"
  post 'comment/:comment_id/unlike', to: 'comments#unlike',as: "unlike_comment"

  #chat
  get '/chat', to: 'rooms#index'
  get '/chat/:id',to: 'chats#show'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  self.per_page = 5
  belongs_to :user
  has_one_attached :banner
  has_rich_text :body
  validates :title ,presence: true ,uniqueness: true ,length: { in:3..100}
  validates :body ,presence: true 
  #,length: { minimum: 25}

  has_many :likes ,dependent: :destroy
  has_many :comments ,dependent: :destroy
  has_many :user_likes ,through: :likes, source: :user
  
  def optimized_image(image,x,y)
    return image.variant(resize_to_fill: [x,y]).processed
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  include MainConcern
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :is_logged_in, only: %i[index edit update destroy like unlike]
  before_action :is_admin, only: %i[index update destroy]
  before_action :is_ban ,only: %i[like unlike new edit create update]
  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
    session[:post_id] = @post.id
    @comment = Comment.new
    if(session[:user_id])
      @self_user = User.find(session[:user_id])
    end
    views = @post.views+1
    @post.update(views: views)
    @user = User.find(@post.user_id)
    if(@post.comments.present?)
      @comments = @post.comments.sort().reverse
    end
  end

  def unlike
    Like.find_by(post_id:params[:post_id] ,user_id:session[:user_id]).destroy
    if(request.referrer)
      redirect_to request.referrer
    end
  end

  def like
    Like.create(post_id:params[:post_id] ,user_id:session[:user_id])
    if(request.referrer)
      redirect_to request.referrer
    end
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
    post = Post.find(params[:id].to_i)
    is_right_user(post.user_id)
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    @post.user_id = session[:user_id]
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id].to_i)
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :description, :user_id, :body,:views,:banner)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_comments.html.haml
- @comments.each do |comment| 
  -user = comment.user
  .card.mb-4{:style => "width:100%;"}
    .row
      .col-2.ms-auto.me-auto
        - if user.avatar.attached?
          = image_tag(user.avatar,:class => "rounded-circle mb-5 mt-5",:style => "width:100px;height:100px; overflow-y:hidden")
        - else
          %img.rounded-circle.mb-5.mt-5{:alt => "default avatar",:src =>image_path("default_avatar.png"),:style => "width:100px;height:100px; overflow-y:hidden"} 
      .col-10.pt-3
        .d-flex.flex-column.align-items-start
          %ul.nav.navbar-nav{:id => "comment-#{user.nickname}"}
            %li.nav-item
              %a.fs-4{:href => "/profile/#{user.nickname}"}
                = user.nickname
            }
            %li.nav-item
              %p.text-muted.fs-6
                = comment.created_at.to_formatted_s(:short)
            %li.nav-item
              %p.fs-4
                = comment.msg
            %li.nav-item
              %p.text-muted.fs-5
                = pluralize(comment.likes.count,"like") 
            %li.nav-item.mb-3
              - if comment.user_likes.include?(@self_user)
                = button_to "Unlike", unlike_comment_path(comment.id) , method: "POST",class:"btn btn-outline-secondary unlike-btn "
              - else
                = button_to "Like", like_comment_path(comment.id) , method: "POST" ,class:"btn btn-outline-primary  like-btn "               
             

.modal.fade{id: "Like",role: "modal","aria-hidden" => "true","taria-labelledby" => "exampleModalLabel",   :tabindex => "-1"}
  .modal-dialog.modal-dialog-scrollable
    .modal-content
      .modal-header
        %h5#exampleModalLabel.w-100.modal-title.text-center User Likes
        %button.btn-close{"aria-label" => "Close", "data-bs-dismiss" => "modal", :type  => "button"}
      .modal-body
        .div#mo_body.container{:style => "font-size:25px"}

:javascript
  $(".showUsers").click(function(){
    $("#mo_body").empty();
    var userJson = $(this).attr("dataModal");
    var userObject = jQuery.parseJSON(userJson);
    userObject.forEach((user) =>{
      var link = `<a class = "card-link-feed" href ="/profile/${user.nickname}"> ${user.nickname} </a> <br><hr>`;
      $("#mo_body").append(link);   
    })
  });

app/views/posts/_form.html.erb
<%= form_with(model: @post) do |form| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% @post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field mb-3 post-title">
    <%= form.label :title ,{ class: "form-label"} %>
    <%= form.text_field :title, { class: "form-control",placeholder: "Title"} %>
  </div>

  <div class="field mb-3">
    <%= form.label :banner ,{ class: "form-label"}%>
    <%= form.file_field :banner, { class: "form-control"} %>
  </div>
  
  <div class="field mb-3">
    <%= form.label :body ,{ class: "form-label"}%>
    <%= form.rich_text_area :body, { class: "form-control",id:"body-rich",placeholder: "Tell me something (Minimum 25 characters)"} %>
  </div>
  <div class="actions">
    <%= form.button :Submit ,class:'btn btn-primary'%>
  </div>
<% end %>

app/views/posts/_showLogin.html.haml
- flash.each do |type, msg|
  .alert.alert-info.alert-dismissible.fade.show{:style => "z-index:9999;"}
    = msg
    %button.btn-close{"aria-label" => "Close", "data-bs-dismiss" => "alert", :type => "button"}

.row
  .col-3.position-fixed.border-end.border-2
    = render '/nav2'

  .col-7.offset-3.ps-5.pe-5
    .container
      %h1.display-4 
        = @post.title
      %hr/
      %p.text-muted.fs-4
        = @post.created_at.to_formatted_s(:short)
        by
        %a{:href => profile_user_path(@post.user.nickname),:method =>"get"}
          = @post.user.nickname
        |
        = pluralize(@post.views,"view")
        |
        = pluralize(@post.likes.count,"like")
        |
        = pluralize(@post.comments.count,"comment")
      .post_body.fs-3
        = @post.body
      - if @post.user_likes.include?(@self_user)
        = button_to "Unlike", unlike_post_path(@post.id) , method: "POST",class:"btn btn-outline-secondary unlike-btn mt-3 mb-3"
      - else
        = button_to "Like", like_post_path(@post.id) , method: "POST" ,class:"btn btn-outline-primary  like-btn mt-3 mb-3"
      - if @post.likes.count != 0 
        %a.showUsers{"data-bs-target" => "#Like", "data-bs-toggle" => "modal", :type => "button","dataModal"=> @post.user_likes.to_json}
          -#----------------number of like------------------
          = @post.likes.count.to_s + " Likes"
      .mt-5
        =render '/comments/form'
      -if(@post.comments.present?)
        .mt-5
          =render 'comments' 

  .col-2.offset-10.position-fixed.border-start.border-2
    = render '/users/profilebar'

.modal.fade{id: "Like",role: "modal","aria-hidden" => "true","taria-labelledby" => "exampleModalLabel",   :tabindex => "-1"}
  .modal-dialog.modal-dialog-scrollable
    .modal-content
      .modal-header
        %h5#exampleModalLabel.w-100.modal-title.text-center User Likes
        %button.btn-close{"aria-label" => "Close", "data-bs-dismiss" => "modal", :type  => "button"}
      .modal-body
        .div#mo_body.container{:style => "font-size:25px"}

:javascript
  $(".showUsers").click(function(){
    $("#mo_body").empty();
    var userJson = $(this).attr("dataModal");
    var userObject = jQuery.parseJSON(userJson);
    userObject.forEach((user) =>{
      var link = `<a class = "card-link-feed" href ="/profile/${user.nickname}"> ${user.nickname} </a> <br><hr>`;
      $("#mo_body").append(link);   
    })
  });

app/views/posts/_showNotLogin.html.haml
- flash.each do |type, msg|
  .alert.alert-info.alert-dismissible.fade.show{:style => "z-index:9999;"}
    = msg
    %button.btn-close{"aria-label" => "Close", "data-bs-dismiss" => "alert", :type => "button"}
= render '/nav'
.div{:style => "width:100%;height:300px; overflow-y:hidden"}
  - if @post.banner.attached?
    = image_tag(@post.banner,style:"width:100%")
  - else
    %img{:alt => "default banner",:src =>image_path("default_banner.jpg"),:style =>"width:100%"}
.container.mt-3
  .container.mt-2
    %h1.display-4 
      = @post.title
    %hr/
    %p.text-muted.fs-4
      = @post.created_at.to_formatted_s(:short)
      by
      %a{:href => profile_user_path(@post.user.nickname),:method =>"get"}
        = @post.user.nickname
      |
      = pluralize(@post.views,"view")
      |
      = pluralize(@post.likes.count,"like")
      |
      = pluralize(@post.comments.count,"comment")
    .post_body.fs-3
      = @post.body
    -if(@post.comments.present?)
      .mt-5
        =render 'comments'

app/views/posts/edit.html.haml
.container
	%h1 Editing post
	
	= render 'form'
	
	= button_to "Show", @post , method: :get ,class:"btn btn-light mt-2"
	= button_to "Back", request.referrer , method: :get ,class:"btn btn-light mt-2"

app/views/posts/index.html.haml
.container
  %h1 Listing posts
  
  
  %table#myTable.table-striped.display{:style => "width:100%"}
    %thead
      %tr
        %th Id
        %th Title
        %th User_id
        %th Views
        %th
        %th
        %th
  
    %tbody
      - @posts.each do |post|
        %tr
          %td= post.id
          %td= post.title
          %td= post.user_id
          %td= post.views
          %td= link_to 'Show', post
          %td= link_to 'Edit', edit_post_path(post)
          %td= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }
  
  
  .d-flex
    = button_to "Users", users_path , method: :get,class:"btn btn-secondary"
    = button_to "Comments", comments_path , method: :get,class:"btn btn-secondary ms-3 "

app/views/posts/new.html.haml
- flash.each do |type, msg|
	.alert.alert-info.alert-dismissible.fade.show{:style => "z-index:9999;"}
		= msg
		%button.btn-close{"aria-label" => "Close", "data-bs-dismiss" => "alert", :type => "button"}
.row
	.col-3.position-fixed.border-end.border-2
		= render '/nav2'
	.col-6.offset-3.ps-5
		.container
			%br
			%br
			%br
			%h1 New post
				
			= render 'form'
			= button_to "back", request.referrer , method: :get,class:"btn btn-light mt-3"

app/views/posts/show.html.haml
-if(session[:user_id])
  =render 'showLogin'
-else
  =render 'showNotLogin'

app/views/posts/temp.haml
= render 'nav'
- @posts.each do |post| 
  - profile_user_name = User.find(post.user_id).name
  .card.mt-4{:style => "width: 50vw;"}
    .card-body.cardPost
      %h5.card-title
        %a.card-link.card-link-feed{:href => "/profile/#{profile_user_name}",:method =>"get",:style => "font-size:25px"}= profile_user_name
      %h6.card-subtitle.mb-2.text-muted= post.created_at.to_formatted_s(:short)
      %pCard.card-text.fst-italic= post.msg
      %br
      - if post.user_likes.include?(@user)
        = button_to "Unlike", unlike_post_path(post.id) , method: "POST",class:"btn btn-primary unlike-btn mt-2"
      - else
        = button_to "Like", like_post_path(post.id) , method: "POST" ,class:"btn btn-secondary  like-btn mt-2"
      - if post.likes.count != 0 
        %button.btn.btn-primary.btn-showUser.mt-2.showUsers{"data-bs-target" => "#Like", "data-bs-toggle" => "modal", :type => "button","dataModal": post.user_likes.to_json}
          -#----------------number of like------------------
          = post.likes.count.to_s + " Likes"